import ClosureFrontier.TheoremTrack.LedgerBoundary

namespace ClosureFrontier.TheoremTrack

-- A presentation of sentence syntax with the preorder a ≤ b read as T ⊢ a → b.
-- This is an interface for an arithmetic theory, not a construction of EA.
-- Computability is on the supplied syntax encoding, never on a Lindenbaum quotient.
structure SentencePresentation (S : Type) [Preorder S] [Primcodable S] where
  conj : S → S → S
  impl : S → S → S
  top : S
  con : S → S
  trueSentence : S → Prop
  consistent : S → Prop
  piClass : ℕ → S → Prop
  conj_left : ∀ a b, conj a b ≤ a
  conj_right : ∀ a b, conj a b ≤ b
  conj_intro : ∀ a b c, a ≤ b → a ≤ c → a ≤ conj b c
  impl_intro : ∀ a b c, conj a b ≤ c → a ≤ impl b c
  impl_elim : ∀ a b, conj a (impl a b) ≤ b
  le_top : ∀ a, a ≤ top
  top_true : trueSentence top
  true_consistent : ∀ a, trueSentence a → consistent a
  conj_computable : Computable₂ conj
  impl_computable : Computable₂ impl
  con_computable : Computable con
  con_monotone : Monotone con

def SentenceEquivalent {S : Type} [Preorder S] (a b : S) : Prop := a ≤ b ∧ b ≤ a

def AgreeModuloCone {S : Type} [Preorder S] (cone : Set S)
    (a b : ExtensionOperator S) : Prop :=
  ∀ x, x ∈ cone → SentenceEquivalent (a.fn x) (b.fn x)

def SliceInvariantModuloCone {S : Type} [Preorder S]
    (slice : FrozenSlice (ExtensionOperator S)) (cone : Set S) : Prop :=
  ∀ a b, AgreeModuloCone cone a b →
    slice.benchmark.yield a = slice.benchmark.yield b ∧ slice.cost.cost a = slice.cost.cost b

def sentenceSetoid (S : Type) [Preorder S] : Setoid S where
  r := SentenceEquivalent
  iseqv := ⟨fun _ => ⟨le_rfl, le_rfl⟩,
    fun h => ⟨h.2, h.1⟩,
    fun h k => ⟨h.1.trans k.1, k.2.trans h.2⟩⟩

theorem sentence_equivalent_iff_quotient_eq {S : Type} [Preorder S] (a b : S) :
    SentenceEquivalent a b ↔
      Quotient.mk (sentenceSetoid S) a = Quotient.mk (sentenceSetoid S) b :=
  ⟨fun h => Quotient.sound (s := sentenceSetoid S) h, fun h => Quotient.exact h⟩

def extensionBy {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (g : S → S) : ExtensionOperator S :=
  ⟨fun φ => P.conj φ (g φ)⟩

theorem extension_by_computable {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) {g : S → S} (hg : Computable g) :
    Computable (extensionBy P g).fn :=
  P.conj_computable.comp Computable.id hg

theorem extension_by_monotone {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) {g : S → S} (hg : Monotone g) :
    Monotone (extensionBy P g).fn := by
  intro a b hab
  exact P.conj_intro _ _ _ ((P.conj_left _ _).trans hab)
    ((P.conj_right _ _).trans (hg hab))

theorem extension_by_strengthens_input {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (g : S → S) (φ : S) : (extensionBy P g).fn φ ≤ φ :=
  P.conj_left _ _

-- The source theorem supplies one of these alternatives. Both use a cone
-- generated by a true sentence, not an arbitrary or preselected set of inputs.
def WalshDichotomy {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (g : S → S) : Prop :=
  (∃ θ, P.trueSentence θ ∧ ∀ φ, φ ≤ θ → φ ≤ g φ) ∨
  (∃ θ, P.trueSentence θ ∧ ∀ φ, φ ≤ θ → P.conj φ (g φ) ≤ P.con φ)

-- External import obligation: Walsh, "A note on the consistency operator",
-- Theorem 2.4. The arithmetic applicability and interpretation of this interface
-- are documented separately. This is a named proof parameter, not a local axiom.
def WalshImportedLaw {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) : Prop :=
  ∀ g : S → S, Computable g → Monotone g →
    (∃ k, ∀ φ, P.piClass k (g φ)) → WalshDichotomy P g

theorem walsh_restricted_canonicalization {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (hWalsh : WalshImportedLaw P)
    (g : S → S) (hComp : Computable g) (hMono : Monotone g)
    (hBound : ∃ k, ∀ φ, P.piClass k (g φ))
    (hStrict : ∀ φ, P.consistent φ → ¬ φ ≤ g φ)
    (hUpper : ∀ φ, P.conj φ (P.con φ) ≤ g φ) :
    ∃ θ, P.trueSentence θ ∧
      AgreeModuloCone {φ | φ ≤ θ} (extensionBy P g) (extensionBy P P.con) := by
  rcases hWalsh g hComp hMono hBound with hWeak | hStrong
  · rcases hWeak with ⟨θ, hTrue, hWeak⟩
    exact (hStrict θ (P.true_consistent θ hTrue) (hWeak θ le_rfl)).elim
  · rcases hStrong with ⟨θ, hTrue, hStrong⟩
    refine ⟨θ, hTrue, ?_⟩
    intro φ hφ
    exact ⟨P.conj_intro _ _ _ (P.conj_left _ _) (hStrong φ hφ),
      P.conj_intro _ _ _ (P.conj_left _ _) (hUpper φ)⟩

theorem frontier_efficiency_transfer_modulo {S : Type} [Preorder S]
    (slice : FrozenSlice (ExtensionOperator S)) (domain : Set (ExtensionOperator S))
    (cone : Set S) (hInv : SliceInvariantModuloCone slice cone)
    (op canonical : ExtensionOperator S) (hEff : FrontierEfficient slice domain op)
    (hAgree : AgreeModuloCone cone op canonical) (hMem : canonical ∈ domain) :
    FrontierEfficient slice domain canonical := by
  rcases hInv op canonical hAgree with ⟨hY, hK⟩
  refine ⟨hMem, ?_⟩
  intro y hy hDom
  apply hEff.2 y hy
  simpa only [FrontierDominates, hY, hK] using hDom

-- All output-equivalence and efficiency facts are obtained in the correct order:
-- arithmetic import -> canonicalization -> invariant-ledger transport.
theorem restricted_arithmetic_frontier_lift {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (hWalsh : WalshImportedLaw P)
    (g : S → S) (hComp : Computable g) (hMono : Monotone g)
    (hBound : ∃ k, ∀ φ, P.piClass k (g φ))
    (hStrict : ∀ φ, P.consistent φ → ¬ φ ≤ g φ)
    (hUpper : ∀ φ, P.conj φ (P.con φ) ≤ g φ) :
    ∃ θ, P.trueSentence θ ∧
      AgreeModuloCone {φ | φ ≤ θ} (extensionBy P g) (extensionBy P P.con) ∧
      Computable (extensionBy P P.con).fn ∧ Monotone (extensionBy P P.con).fn ∧
      ∀ (slice : FrozenSlice (ExtensionOperator S)) (domain : Set (ExtensionOperator S)),
        SliceInvariantModuloCone slice {φ | φ ≤ θ} →
        FrontierEfficient slice domain (extensionBy P g) →
        extensionBy P P.con ∈ domain →
        FrontierEfficient slice domain (extensionBy P P.con) := by
  rcases walsh_restricted_canonicalization P hWalsh g hComp hMono hBound hStrict hUpper
    with ⟨θ, hTrue, hAgree⟩
  refine ⟨θ, hTrue, hAgree, extension_by_computable P P.con_computable,
    extension_by_monotone P P.con_monotone, ?_⟩
  intro slice domain hInv hEff hMem
  exact frontier_efficiency_transfer_modulo slice domain _ hInv _ _ hEff hAgree hMem

-- Concrete operation: guard the consistency sentence by one fixed true sentence.
-- For EA take θ = Con(EA). The arithmetic interpretation and the Gödel import
-- supplying truth/unprovability are external; the displayed logical bridge is proved.
def guardedConsistency {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (θ : S) (φ : S) : S := P.impl θ (P.con φ)

theorem guarded_consistency_computable {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (θ : S) : Computable (guardedConsistency P θ) :=
  P.impl_computable.comp (Computable.const θ) P.con_computable

theorem impl_monotone_right {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (θ : S) : Monotone (P.impl θ) := by
  intro a b hab
  exact P.impl_intro _ _ _
    (le_trans (P.conj_intro _ _ _ (P.conj_right _ _) (P.conj_left _ _))
      ((P.impl_elim θ a).trans hab))

theorem guarded_consistency_monotone {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (θ : S) : Monotone (guardedConsistency P θ) :=
  (impl_monotone_right P θ).comp P.con_monotone

theorem guarded_consistency_canonicalization {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (θ : S) :
    AgreeModuloCone {φ | φ ≤ θ}
      (extensionBy P (guardedConsistency P θ)) (extensionBy P P.con) := by
  intro φ hφ
  constructor
  · apply P.conj_intro _ _ _ (P.conj_left _ _)
    exact (P.conj_intro _ _ _ ((P.conj_left _ _).trans hφ) (P.conj_right _ _)).trans
      (P.impl_elim θ (P.con φ))
  · apply P.conj_intro _ _ _ (P.conj_left _ _)
    apply P.impl_intro
    exact (P.conj_left _ _).trans (P.conj_right _ _)

theorem guarded_consistency_strict_on_support {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (θ : S)
    (hGodel : ∀ φ, P.consistent φ → ¬ φ ≤ P.con φ)
    (φ : S) (hConsistent : P.consistent φ) (hSupport : φ ≤ θ) :
    (extensionBy P (guardedConsistency P θ)).fn φ ≤ φ ∧
      ¬ φ ≤ (extensionBy P (guardedConsistency P θ)).fn φ := by
  refine ⟨P.conj_left _ _, ?_⟩
  intro h
  have hAgree := guarded_consistency_canonicalization P θ φ hSupport
  exact hGodel φ hConsistent (h.trans (hAgree.1.trans (P.conj_right _ _)))

-- An outside-cone negative control. With θ = Con_T(top), the guarded
-- extension of top adds nothing, whereas the canonical extension adds consistency.
theorem guarded_disagrees_outside_support {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (hGodel : ¬ P.top ≤ P.con P.top) :
    ¬ P.top ∈ ({φ | φ ≤ P.con P.top} : Set S) ∧
      ¬ SentenceEquivalent
        ((extensionBy P (guardedConsistency P (P.con P.top))).fn P.top)
        ((extensionBy P P.con).fn P.top) := by
  refine ⟨hGodel, ?_⟩
  intro hEq
  have hGuard : P.top ≤ P.impl (P.con P.top) (P.con P.top) :=
    P.impl_intro _ _ _ (P.conj_right _ _)
  have hNoChange : P.top ≤
      (extensionBy P (guardedConsistency P (P.con P.top))).fn P.top :=
    P.conj_intro _ _ _ le_rfl hGuard
  exact hGodel (hNoChange.trans (hEq.1.trans (P.conj_right _ _)))

-- One declared arithmetic benchmark: the output proves the consistency of T+probe.
-- The score is noncomputable in general. Syntax effectivity does not make the
-- theorem/provability benchmark decidable. The cost is fixed at zero.
noncomputable def consistencyProbeSlice {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (probe : S) : FrozenSlice (ExtensionOperator S) := by
  classical
  exact { benchmark := ⟨fun op => if op.fn probe ≤ P.con probe then 1 else 0⟩
          cost := ⟨fun _ => 0⟩
          transformationClass := fun _ _ => True }

theorem consistency_probe_invariant {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (probe : S) (cone : Set S) (hProbe : probe ∈ cone) :
    SliceInvariantModuloCone (consistencyProbeSlice P probe) cone := by
  classical
  intro a b hab
  have hEq := hab probe hProbe
  have hiff : a.fn probe ≤ P.con probe ↔ b.fn probe ≤ P.con probe :=
    ⟨fun ha => hEq.2.trans ha, fun hb => hEq.1.trans hb⟩
  exact ⟨by simp [consistencyProbeSlice, hiff], rfl⟩

theorem consistency_probe_efficient {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (probe : S) (domain : Set (ExtensionOperator S))
    (op : ExtensionOperator S) (hMem : op ∈ domain) (hPass : op.fn probe ≤ P.con probe) :
    FrontierEfficient (consistencyProbeSlice P probe) domain op := by
  classical
  refine ⟨hMem, ?_⟩
  intro y _
  by_cases hy : y.fn probe ≤ P.con probe
  · simp [FrontierDominates, consistencyProbeSlice, hy, hPass]
  · simp [FrontierDominates, consistencyProbeSlice, hy, hPass]

theorem consistency_probe_separates_identity {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (probe : S) (hGodel : ¬ probe ≤ P.con probe) :
    (consistencyProbeSlice P probe).benchmark.yield (extensionBy P P.con) = 1 ∧
      (consistencyProbeSlice P probe).benchmark.yield ⟨id⟩ = 0 ∧
      FrontierDominates (consistencyProbeSlice P probe) (extensionBy P P.con) ⟨id⟩ := by
  classical
  have hc : (extensionBy P P.con).fn probe ≤ P.con probe := P.conj_right _ _
  simp [consistencyProbeSlice, hc, hGodel, FrontierDominates]

-- Inhabited support, computed monotone maps, nonconstant invariant scores,
-- efficient representatives, and a dominated control, all in one declared domain.
theorem guarded_consistency_frontier_instance {S : Type} [Preorder S] [Primcodable S]
    (P : SentencePresentation S) (θ : S) (hTrue : P.trueSentence θ)
    (hGodel : ¬ θ ≤ P.con θ) :
    P.trueSentence θ ∧
    Computable (extensionBy P (guardedConsistency P θ)).fn ∧
    Monotone (extensionBy P (guardedConsistency P θ)).fn ∧
    Computable (extensionBy P P.con).fn ∧ Monotone (extensionBy P P.con).fn ∧
    AgreeModuloCone {φ | φ ≤ θ}
      (extensionBy P (guardedConsistency P θ)) (extensionBy P P.con) ∧
    SliceInvariantModuloCone (consistencyProbeSlice P θ) {φ | φ ≤ θ} ∧
    FrontierEfficient (consistencyProbeSlice P θ)
      {extensionBy P (guardedConsistency P θ), extensionBy P P.con, ⟨id⟩}
      (extensionBy P (guardedConsistency P θ)) ∧
    FrontierEfficient (consistencyProbeSlice P θ)
      {extensionBy P (guardedConsistency P θ), extensionBy P P.con, ⟨id⟩}
      (extensionBy P P.con) ∧
    FrontierDominates (consistencyProbeSlice P θ) (extensionBy P P.con) ⟨id⟩ := by
  have hAgree := guarded_consistency_canonicalization P θ
  have hPass : (extensionBy P (guardedConsistency P θ)).fn θ ≤ P.con θ :=
    ((hAgree θ le_rfl).1).trans (P.conj_right _ _)
  refine ⟨hTrue, extension_by_computable P (guarded_consistency_computable P θ),
    extension_by_monotone P (guarded_consistency_monotone P θ),
    extension_by_computable P P.con_computable, extension_by_monotone P P.con_monotone,
    hAgree, consistency_probe_invariant P θ _ le_rfl, ?_, ?_,
    (consistency_probe_separates_identity P θ hGodel).2.2⟩
  · exact consistency_probe_efficient P θ _ _ (by simp) hPass
  · exact consistency_probe_efficient P θ _ _ (by simp) (P.conj_right _ _)

end ClosureFrontier.TheoremTrack
