#!/usr/bin/env python3
"""Generate data-driven TikZ figures for the manuscript from shipped result tables.

Writes paper/figures/fig_comparators.tex and paper/figures/tab_comparators.tex from
results/ticket-p6-1/interaction_delta_table.csv.
No experiment is run; the figure only re-plots saved descriptive comparisons.
"""
from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "results" / "ticket-p6-1" / "interaction_delta_table.csv"
OUT = ROOT / "paper" / "figures" / "fig_comparators.tex"
TABLE_OUT = ROOT / "paper" / "figures" / "tab_comparators.tex"

XMIN, XMAX = -0.8, 0.4
PANEL_W = 5.4  # cm, plotting width per panel
ROW_H = 0.36  # cm per configuration


def tex_name(name: str) -> str:
    return name.replace("_", r"\_")


def main() -> int:
    with SOURCE.open(newline="") as handle:
        rows = [r for r in csv.DictReader(handle) if r["n_tier"] == "core"]
    configs = sorted({r["config_name"] for r in rows})
    by_key = {(r["config_name"], int(r["n"])): r for r in rows}
    scales = sorted({int(r["n"]) for r in rows})
    assert len(rows) == len(configs) * len(scales), "expected one core row per (config, scale)"

    def xpos(value: float) -> float:
        return (value - XMIN) / (XMAX - XMIN) * PANEL_W

    lines = [
        "% Generated by scripts/make_paper_figures.py from",
        "% results/ticket-p6-1/interaction_delta_table.csv -- do not edit by hand.",
        r"\begin{tikzpicture}[font=\footnotesize]",
    ]
    height = ROW_H * (len(configs) - 1)
    for panel, n in enumerate(scales):
        ox = panel * (PANEL_W + 1.4)
        lines.append(rf"\begin{{scope}}[xshift={ox:.2f}cm]")
        # recessive gridlines and zero reference
        for tick in [-0.8, -0.6, -0.4, -0.2, 0.0, 0.2, 0.4]:
            x = xpos(tick)
            style = "black!55, line width=0.6pt" if tick == 0.0 else "black!12, line width=0.4pt"
            lines.append(rf"\draw[{style}] ({x:.3f},-0.25) -- ({x:.3f},{height + 0.25:.3f});")
            lines.append(rf"\node[below, black!70, font=\scriptsize] at ({x:.3f},-0.25) {{{tick:+.1f}}};".replace("+0.0", "0"))
        lines.append(rf"\node[font=\footnotesize\bfseries] at ({PANEL_W / 2:.3f},{height + 0.6:.3f}) {{$n={n}$}};")
        for i, config in enumerate(configs):
            y = height - i * ROW_H
            r = by_key[(config, n)]
            near = float(r["interaction_delta_abs_shift"])
            best = float(r["gain_over_best_absolute_shift"])
            lines.append(rf"\draw[black!30, line width=1pt] ({xpos(near):.3f},{y:.3f}) -- ({xpos(best):.3f},{y:.3f});")
            lines.append(rf"\node[rectangle, fill=seriesB, draw=white, line width=0.6pt, inner sep=1.9pt] at ({xpos(best):.3f},{y:.3f}) {{}};")
            lines.append(rf"\node[circle, fill=seriesA, draw=white, line width=0.6pt, inner sep=1.9pt] at ({xpos(near):.3f},{y:.3f}) {{}};")
            if panel == 0:
                lines.append(rf"\node[anchor=east, font=\scriptsize\ttfamily] at (-0.1,{y:.3f}) {{{tex_name(config)}}};")
        lines.append(rf"\node[black!70, font=\scriptsize] at ({PANEL_W / 2:.3f},-0.85) {{gain in $|\Delta\,\mathrm{{frob}}|$ over comparator}};")
        lines.append(r"\end{scope}")
    # legend
    ly = height + 1.15
    lines.append(rf"\node[circle, fill=seriesA, inner sep=1.9pt] at (0.2,{ly:.3f}) {{}};")
    lines.append(rf"\node[anchor=west] at (0.35,{ly:.3f}) {{vs.\ nearest nonempty proper subprogram}};")
    lines.append(rf"\node[rectangle, fill=seriesB, inner sep=1.9pt] at (6.6,{ly:.3f}) {{}};")
    lines.append(rf"\node[anchor=west] at (6.75,{ly:.3f}) {{vs.\ best measured proper subprogram}};")
    lines.append(r"\end{tikzpicture}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} core comparisons)")

    table = [
        "% Generated by scripts/make_paper_figures.py -- do not edit by hand.",
        r"\begin{tabular}{@{}l r l r r@{}}",
        r"\toprule",
        r"Configuration & $n$ & Nearest comparator & Gain (nearest) & Gain (best) \\",
        r"\midrule",
    ]
    for config in configs:
        for n in scales:
            r = by_key[(config, n)]
            table.append(
                rf"\texttt{{{tex_name(config)}}} & {n} & \texttt{{{tex_name(r['closest_simpler_config'])}}} & "
                rf"${float(r['interaction_delta_abs_shift']):+.3f}$ & ${float(r['gain_over_best_absolute_shift']):+.3f}$ \\"
            )
    table += [r"\bottomrule", r"\end{tabular}"]
    TABLE_OUT.write_text("\n".join(table).replace("$+0.000$", "$0.000$") + "\n", encoding="utf-8")
    print(f"wrote {TABLE_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
